version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          working_directory: backend
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test-backend
